[env]
GOPROXY = '{% if env.CI is defined %}https://proxy.golang.org,direct{% else %}https://goproxy.cn,direct{% endif %}'
GOSUMDB = '{% if env.CI is defined %}sum.golang.org{% else %}sum.golang.google.cn{% endif %}'

[tools]
go = "1.26.5"
